INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Amy Amadea', 'aamadea@kemana.com', 'Backend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Anan Fauzi', 'afauzi@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Ansyori B', 'ansyori@kemana.com', '', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Arvin Arvin Kurniawan', 'akurniawan@kemana.com', 'Office Manager', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Ashadi Muliawan', 'amuliawan@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Bobby Brillian Yerikho', 'bbyerikho@kemana.com', 'Backend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Budi Hriyana', 'bhariyana@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Christopher Benz', 'cbenz@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Cindy Kitty Heronita', 'ckitty@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Cipto Raharjo', 'craharjo@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Didi Kusnadi', 'dkusnadi@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Didiet Nur Cahyanto', 'didiet@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Edi Suryadi', 'esuryadi@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Fajar Indra', 'findra@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Fikri Abdilah', 'fabdilah@kemana.com', 'Mobile Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Firman Alhadiansyah', 'falhadiansyah@kemana.com', 'Backend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Gen Gen Fikri Adam', 'gfadam@kemana.com', 'Backend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Hafizh Fathir Firdaus', 'hffirdaus@kemana.com', 'Backend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Henry Wongkar', 'hwongkar@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Hernady Latip', 'hlatip@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Herwandi', 'herwandi@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Imam Kusuma', 'ikusuma@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Irman Pambudi', 'ipambudi@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Jeffry Yudha Putra', 'jyputra@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Kamaludin', 'kamaludin@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Kevin Gosal', 'kgosal@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Kurniawan', 'kurniawan@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Mahardhika Putra Sulistyo', 'mpsulistyo@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Miranitha Fasha', 'mfasha@kemana.com', 'Backend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Muttaqiin', 'muttaqiin@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Norisa Rorah', 'nrorah@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Pendi', 'pendi@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Ratna Puri Effendi', 'rpeffendi@kemana.com', 'Frontend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Ratu Dita', 'rdita@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Rizal Fauzie Ridwan', 'rfridwan@kemana.com', 'Frontend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Romauli Oktohana', 'mhana@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Ryan Permana', 'rpermana@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Saiful Fahamsyah', 'sfahamsyah@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Sapta Sanjaya', 'ssanjaya@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Shinta Octavia', 'soctavia@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Sidik Purnomo', 'spurnomo@kemana.com', 'Backend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Simon Petrus', 'spetrus@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Sonny Ariestiawan', 'sariestiawan@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Syahfitria Syarifuddin', 'ssyarifuddin@kemana.com', 'Backend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Tata Arpandi', 'tarpandi@kemana.com', '', 'Kemana Jakarta', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Taufik Maulana Nugraha', 'tmnugraha@kemana.com', 'Frontend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);
INSERT INTO `staff` (`name`, `email`, `position`, `location`, `status`, `timestamp`) VALUES('Taupik Otto Ismail', 'toismail@kemana.com', 'Frontend Developer', 'Kemana Bandung', 'Active', CURRENT_TIMESTAMP);



INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-001', 'Mac', 'Macbook Pro', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-002', 'Dell', 'Inspiron 14 3000 Series', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-002a', 'Toshiba', 'Satellite C800-1024', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-003', 'ASUS', 'A450CA-WX104D', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-004', 'ASUS', 'A46CB-WX025D', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-004a', 'ASUS', ' X455LA-WX081D', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-005', 'Lenovo', 'Notebook Lenovo G450', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-006', 'Mac', 'Macbook Pro A1278', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-007', 'Fujitsu', 'LifeBook L Series LH532', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-008', 'Lenovo', 'G450', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-009', 'Mac', 'Macbook Pro', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-010', 'Fujitsu', 'LifeBook L Series LH532', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-011', 'Lenovo', 'G450', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-012', 'Toshiba', 'Satellite C800-1024', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-013', 'Dell', 'Inspiron 3442', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-014', 'ASUS', 'X455LA-WX669D', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-015', 'ASUS', 'A46CB-WX025D', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-016', 'ASUS', 'A450C', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-017', 'ASUS', 'X450CA-WX242D', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-020', 'ASUS', 'A450C', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-022', 'ASUS', 'X451CA-VX126D', '', '', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-023', 'Acer', 'Aspire E5-471G', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-025', 'ASUS', 'X555L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-026', 'ASUS', 'X555L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-027', 'ASUS', 'X555L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-028', 'ASUS', 'A456U', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-029', 'ASUS', 'X456UF', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-030', 'ASUS', 'X456UF', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-031', 'ASUS', 'X455LJ', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-032', 'ASUS', 'A455L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-033', 'ASUS', 'X455LJ', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-034', 'ASUS', 'X450CA', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-035', 'ASUS', 'X540L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-036', 'ASUS', 'A455L', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-037', 'ASUS', 'A455L', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-038', 'ASUS', 'A455L', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-039', 'ASUS', 'A455L', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-040', 'ASUS', 'A455L', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-041', 'ASUS', 'A455L', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-042', 'ASUS', 'A455L', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-043', 'ASUS', 'A455L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-043a', 'ASUS', 'A455L', 'Kemana Bandung', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-044', 'ASUS', 'A455L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-049', 'ASUS', 'A455L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-050', 'ASUS', 'A455L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-051', 'ASUS', 'A455L', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-052', 'ASUS', 'A456U', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-053', 'ASUS', 'A456U', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-054', 'ASUS', 'A456U', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);
INSERT INTO `hardware` (`category`, `name`, `label`, `manufacturer`, `series`, `location`, `condition`, `timestamp`) VALUES('pc', 'Laptop', 'KSL-055', 'ASUS', 'A456U', 'Kemana Jakarta', 'Good', CURRENT_TIMESTAMP);

